FROM node:16-alpine

# Create app directory
WORKDIR /app
# Install app dependencies
COPY package*.json ./
RUN yarn install

# Copy app source code
COPY . .
RUN yarn global add typescript
RUN yarn global add ts-node

# Compile TypeScript
RUN yarn build

# Start the server
CMD [ "yarn", "start" ]
